version: '3.9'
services:
  router:
    hostname: ingress.mihuatuanzi.io
    image: seanscraft/com.mihuatuanzi.router:latest
    build:
      context: .
      target: router
    deploy:
      update_config:
        order: start-first
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - default
