http:
  routers:
    mihuatuanzi:
      rule: Host(`backend.mihuatuanzi.com`)
      service: mihuatuanzi-backend
      entryPoints:
      - web

  services:
    mihuatuanzi-backend:
      loadBalancer:
        servers:
        - url: http://backend.proxy.mihuatuanzi.io
        passHostHeader: false
